### ISSUE TITLE
Do we need a separate repo for finance?

### ISSUE THREAD

**Issue by iteles** [dwyl/finance#3]
I have a preference to keep everything 'administrative' in a single repo for dwyl so it's out of the way.

I would suggest [merging this repo](http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories) with [`hq`](https://github.com/dwyl/hq) and adding a `finance` label to that repo 😊 

What are your thoughts @markwilliamfirth ?

**Comment by markwilliamfirth** [comment]
Concerned the `hq` might get a little messy / cumbersome, although you know Github better than I so there are probably reasons I don't know that it's better in a single repo.

I have added the `finance` label in `hq`, will merge 👍

**Comment by markwilliamfirth** [comment]
Is this the best way, @iteles ?

To merge `project-a` into `project-b`:
>cd path/to/project-b
git remote add project-a path/to/project-a
git fetch project-a
git merge --allow-unrelated-histories project-a/master # or whichever branch you want to merge
git remote remove project-a

**Comment by iteles** [comment]
http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by markwilliamfirth** [comment]
Yes I saw the link, the accepted answer has 253 votes, but there is another answer with 571 votes (the one I pasted above). I've never done it before, so was wondering if you had a preference for how to do it?

**Comment by markwilliamfirth** [comment]
Has someone else done this before? Wanted to check it's the best way before I go ahead and break something 😬

**Comment by iteles** [comment]
Seems sensible. I would suggest you try merging this repo and contracts before merging the resulting repo into hq which is the one we really don't want to break!

**Comment by markwilliamfirth** [comment]
closing finance repo
